name: LambdaEconomy
version: '${project.version}'
main: at.lambdaspg.lambdaeconomy.LambdaEconomy
api-version: 1.16
authors: [ LambdaSpg ]
depend: [Vault]
description: Economy Plugin

commands:
  ecoset:
    description: EcoSet
  ecoget:
    description: EcoGet
    aliases: [money, bal, balance]